### ISSUE TITLE
do not fall for this

### ISSUE THREAD

**Issue by minksW** [jbspot/iOS-17-Jailbreak#1]
go to the actual guide for help

**Comment by Zyglorp** [comment]
You're so real for this

**Comment by prodHazo** [comment]
where is the actual guide?

**Comment by jbspot** [comment]
will update guides

**Comment by opa334** [comment]
> will update guides

just delete the repo, dude

**Comment by jbspot** [comment]
Already guides updated

**Comment by opa334** [comment]
The real guide is ios.cfw.guide, all the "jailbreaks" you list in your guide here are fake, but I'm fairly sure you're aware of that already...
